### ISSUE TITLE
Git Kraken on Chrome OS

### ISSUE THREAD

**Issue by ramonsito21** [cop1000/201720#4]
Hello, i'm trying to download git kraken before atom. The problem im having is it wont download because im using a chrome computer running the software chrome os. Is there another way to download the application or anything i can do? On the professors video it's called github desktop. Is there a difference?

**Comment by Marinovp** [comment]
@ramonsito21 see the link below:
http://www.howtogeek.com/173353/how-to-run-windows-software-on-a-chromebook/

Specifically the section that says "Use Developer Mode and Install Wine"

**Comment by ramonsito21** [comment]
@Marinovp Thank you for the advice very helpfull. First i'm going to try on my other windows computer but it's super slow, if not i will use the chrome.

**Comment by DLiberal** [comment]
make sure the OS is up to date. Before the listed steps, have Gitkraken installed and running. Also, if any issues occur while using atom, reinstall it. After doing so, locate the README.md file (open it using atom) and make the desired changes pertaining to your question.

**Comment by hectorsector** [comment]
Thanks for the amazing help @marinovp @dliberal

@ramonsito21 let us know if any of the suggestions work. There's also a great suggestion by @dabouelhassan [in chat](https://cop1000valencia.slack.com/archives/open-hangout/p1484704341000006). Please let us know how it turns out!

If you

**Comment by ramonsito21** [comment]
Well later i would have to try on my other computer because i cant do it on the chrome.

**Comment by ramonsito21** [comment]
so far it has been working how can I add my answer like the professor did on the video?

**Comment by ramonsito21** [comment]
Tried to add my answer but every time I opened file with atom it would close and reinstall. I added the answer to "revert add answer to question 17" clicked on push but didn't give me much after that.

**Comment by hectorsector** [comment]
@ramonsito21 you can open Atom separately, or really use any other text editor. You don't have to use Atom. Since this issue was about Git Kraken on Chrome OS I'm going to go ahead and close it, but please feel free to open a new one about Atom if it's still giving you trouble.
